version: '3.8'

services:
  teleagent:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dtdl_teleagent_ai
    ports:
      - "8000:8000"
    env_file:
      - .env
    restart: unless-stopped
